### ISSUE TITLE
❓👂 Question/Feedback - Explain when linter warnings should be disabled

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure/ALZ-Bicep#153]
## Question/Feedback

I notice that location linter warning is disabled for certain modules and it's unclear why these should be.

Generally, ignoring linter warnings can lead to poor code quality so trying to understand when one should disable linter rules like this and when to resolve them.

Example:  https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep

```
module modCustomerUsageAttribution '../../CRML/customerUsageAttribution/cuaIdResourceGroup.bicep' = if (!parTelemetryOptOut) {
  #disable-next-line no-loc-expr-outside-params
  name: 'pid-${varCuaid}-${uniqueString(resourceGroup().location)}'
  params: {}
}
```

**Comment by jtracey93** [comment]
Hey @SenthuranSivananthan. Thanks for raising this. There is indeed a valid reason for doing this and this you’ll notice is only for the `modCustomerUsageAttribution` modules as we want to ensure that, that deployment stays with the location of the deployment rather than the location from the parameters from something like `parRegion` or `parLocation` (which may be different).

I'll get a comment raised in all the modules in-line to cover this 👍
