### ISSUE TITLE
💡 Feature Request - Add subscription management group placement

### ISSUE THREAD

**Issue by johnlokerse** [Azure/ALZ-Bicep#211]
## Describe the solution you'd like

The current [creation of subscriptions](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/CRML/subscriptionAlias/subscriptionAlias.bicep) places the subscription in the Tenant Root Group or other default management group. 

I would like to add the "move feature" to this Bicep template. This will be an optional feature and uses the `parManagementGroupId` to define the subscription placement location. I am not sure if this feature fits the vision of the repository, so that's why I made this request.

**Comment by johnlokerse** [comment]
Scrolled through the modules and saw a placement module... What is the reason that this is separated from the creation of subscriptions?

**Comment by jtracey93** [comment]
Hey @johnlokerse,

Thanks for raising this and glad you found the separate module. 👍

The reason for this separation is so that it can be called individually or from an orchestration template if desired. One of our key principles for ALZ-Bicep was to be modular, where possible and appropriate, based on customer feedback we heard loud and clear on the ARM templates we had before that support the portal deployment today.

The `subAlias` module today however, does support placing the sub into an existing management group, that is optional:
https://github.com/Azure/ALZ-Bicep/blob/98a395828877dea6e6361369683966fecd6331a5/infra-as-code/bicep/CRML/subscriptionAlias/subscriptionAlias.bicep#L21-L22

### Question

So, what is it that is missing from what's already available today? @johnlokerse 

### Side Note

We are also aware that the bug preventing us building end to end orchestration modules to do the whole ALZ deployment is now fixed, so in our next sprint (May) we will be looking to get these completed and out the door 👍 These will include sub placement as part of a single module.

Thanks

Jack

**Comment by johnlokerse** [comment]
Ah, I understand. I was looking from another perspective. My ideal view is to have one Bicep template per subject, for example, createSubscription.bicep, which does everything you need to do surrounding creating subscriptions and in my case also moving them to other management groups. 

To verify if I understand it correctly; do you mean that my solution is achievable using a "main.bicep" which uses the "subAlias.bicep" and "subPlacement.bicep" as modules in the main file?

**Comment by jtracey93** [comment]
Hey @johnlokerse,

Exactly that 👍 Providing ultimate flexibility.

However, you can do this all today upon creation using the `subAlias` module and it will put it in an existing management group - is this not your requirement in a single module?

Or are you looking to move the subscription around in the hierarchy at a later date, which isn't possible with the `subAlias` module due to the way the `alias` API works today? (it's a one time operation)

We normally see customers create a orchestration module mapping combining the `managementGroups` module with the `subPlacement` module to manage the arranging/placement of subscriptions. But importantly outside of the creation operation/module.

Then they just ensure that at sub creation time it is placed correctly to start with and then they add into the above mentioned orchestration module, of MGs and Sub Placement, for ongoing management/placement of the sub. 

Generally these are separate pipelines or steps in a single pipeline.

Does that makes sense and help?

Let me know

Thanks

Jack

**Comment by johnlokerse** [comment]
That makes sense! I didn't know there was a subscription placement module present, so that's why I created the request. We sort of forked the ALZ-Bicep repository but didn't see the module from ALZ-Bicep in our repo (we created our own), so I assumed it wasn't there.

Our setup:
Main
```bicep
targetScope = 'tenant'

... our properties ...

module modCreateSubscription 'createSubscription.bicep' = [for subProperties in parSubscriptionProperties: {
  name: 'Deploy-Sub-${SubName}'
  params: {
... our params ...
  }
}]
```

createSubscription.bicep
```bicep
... our input params ...

module modTags '../tags/tagging.module.bicep' = {
... our tagging module ...
}

resource resSubscription 'Microsoft.Subscription/aliases@2021-10-01' = {
  name: parSubscriptionProperties.Name
  properties: {
... our subscription properties ...
  }
}

module modMoveSubscriptionToMg 'subMgPlacement.bicep' = {
  name: 'Move-Sub-${parSubscriptionProperties.Name}'
  scope: managementGroup(parTenantParentMg)
  params: {
     SubscriptionId: resSubscription.properties.subscriptionId
  }
}
```

Subtracted some properties and parameters. The output of the resource `resSubscription` is used in our placement module. Good to know we are on the right track. Thanks for your quick response 🙂

**Comment by jtracey93** [comment]
No worries. Ill close this one out 👍
