### ISSUE TITLE
objectid needs to be changed to id

### ISSUE THREAD

**Issue by kunalbawankule** [Azure/ALZ-Bicep#275]
The cli command to query object id needs to be changed in the role assignment module.
For ex. az ad group show --group <SECURITY_GROUP_NAME> --query **objectId** - This is the current command.
az ad group show --group <SECURITY_GROUP_NAME> --query **id** - This is the updated.

**Comment by johnlokerse** [comment]
Hi @jtracey93, can I pick this up?

**Comment by johnlokerse** [comment]
> @johnlokerse can you also check for any other places in the docs/modules where this needs updating 👍👍

I will do that 😃

**Comment by johnlokerse** [comment]
Just did some checks and the "id" is indeed correct but the CLI output is not correct. Although, if you look at the manifest of the app registration the "id" equals the object id of the app registration.

@jtracey93 can you check if you have the same behavior on your side? See the CLI output versus the portal values on my screenshot:

![image](https://user-images.githubusercontent.com/3514513/177939738-e05e2dbb-2286-4d6b-8617-73094f8423ba.png)

**Comment by jtracey93** [comment]
Hey @johnlokerse,

Think this is correct from my testing
![image](https://user-images.githubusercontent.com/41163455/177977284-330409a4-a202-493c-921b-024c6629dcfb.png)
![image](https://user-images.githubusercontent.com/41163455/177977345-0100ce52-adc0-4e3d-91a2-d7e33f6669b9.png)

Are you looking at the object ID on the app registration page instead of the enterprise app page? Enterprise app is the ID we need :)

**Comment by johnlokerse** [comment]
Ah, I see... was looking at the wrong page. 😄
