### ISSUE TITLE
❓👂 Question/Feedback - How to consume hubPeeredSpoke module ? 

### ISSUE THREAD

**Issue by stalejohnsen** [Azure/ALZ-Bicep#327]
## Question/Feedback

I'm trying to deploy hubPeeredSpoke module for **Identity** vnet, peering and udr, that works fine but how should it be consumed at the next stage to deploy subnet, nsg and attach nsg/udr to the subnet for that pre-existing vnet from hubPeeredSpoke module? ARM doesn't really like to have subnets as a seperate child resource and you get into conflicts like this: https://github.com/Azure/bicep/issues/4653 

The identity scenario here is solvable with some customization but it would be very valuable with some additional guidance / examples in the wiki on how the platform team deployed spoke vnet can be consumed by app teams to create child resources in seperate IaC definition.I see similarity with subscription vending machine here?

## Possible Answers/Solutions?

I could modify the hubPeeredSpoke module to create a custom Identity module with all the required platform identity resources and then avoid conflicts for that specific use case since i'm working with platform resources.

**Comment by jtracey93** [comment]
Hey @stalejohnsen,

A lot of this will come down to the operating model of the teams operating the platform side and the application LZ side.

This module is meant to be used by the Platform team to help them provision base networking resources into an app teams LZ subscription. And app team wouldn't likely be able to use or deploy this module as they won't have the required RBAC to deploy and configure resources on the hub/connectivity subscription side (and rightly so).

Unfortunately, today, as you have found, ARM doesn't like subnets as child resources and should ideally be declared within the vNet resource. However, today in ALZ-Bicep we have decided not to add subnet support for spoke vNets as documented here in the [`spokeNetworking.bicep` module](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/spokeNetworking#note) due to this complexity. #

We are awaiting customTypes support in Bicep which will help us keep complex arrays/objects easily to declare and use within Bicep with things like intellisense, which today are not available and hence why we don't want to start adding the subnets into our spoke networking modules as it can become very complex with lots of properties, very quickly. And all without IDE support and having to go through painful trial and error to get a successful deployment if we enabled complex objects/arrays to allow subnet deployment. 

> We had a previous issue asking about subnet support here #301 where we discussed this at length and led to the docs being updated on the `spokeNetworking.bicep` module

## What do we suggest

If app teams are being allowed to deploy/manage/configure their vNets and associated resources then they should firstly decide what tool they are going to use to do this. Will it be IaC (Bicep, ARM, Terraform etc.) or will it be the portal? Both are fine options based on that teams skills etc. and policy-driven governance will ensure they do it correctly based on governance/security requirements, regardless of the tool they use.

If they do choose to use Bicep for example (which I think you are leaning towards here) they should build/create/adopt their own spoke vNet module/bicep file in their Git repo and their own CI/CD which will only have access to their subscription. As per the note on the [`spokeNetworking.bicep` module](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/spokeNetworking#note) we make some suggestions on how to approach this in Bicep. CARML is a good place to start for those more advanced and for those that arent, they could take the ALZ-Bicep `spokeNetworking.bicep` as inspiration and add subnet support to it.

From there they can configure it to be exactly the same as what is already deployed and validate with [what-if](https://learn.microsoft.com/azure/azure-resource-manager/bicep/deploy-what-if?tabs=azure-powershell%2CCLI) to ensure no changes are going to be made they aren't expecting and then once happy push onto an actual deployment and then they can go on from there.

Does this help?

> Identity can be though of as just another application landing zone JFYI, it just happens to sometimes be managed by the same central IT team as the rest of the platform. But will it always be like that? Is it a good idea to break it out into its own repo as per other app LZs? All important things to consider for future agility.
