### ISSUE TITLE
❓👂 Question/Feedback - Orchestration Modules, Complete Deployment

### ISSUE THREAD

**Issue by ArthiSaravana** [Azure/ALZ-Bicep#424]
Question

1) Is it possible to deploy a azure landing zone (hub includes many management groups, subscriptions and resources within it ) in just with one main bicep file and with many modules bicep file?

**Comment by jtracey93** [comment]
Hey @ArthiSaravana,

Thanks for the issue. 

You can indeed stitch all of the modules together in a bicep file to create a single deployment. You just need to ensure dependencies are correct as per the wiki deployment flow docs. 

We have this on our backlog, but are yet to prioritise as has not been commonly asked for to date. We heard more that folks wanted it to be modular as possible, hence what we have delivered today 👍

What architecture would you be looking  for in a complete end to end orchestration bicep file? 

We would highly recommend not deploying all of ALZ and the workloads into the landing zone in a single bicep file as this is a very large deployment and would typically be done by different operational teams. 

Let us know.

**Comment by ArthiSaravana** [comment]
Want to deploy hub and spoke architecture in one deployment is it possible? or atleast hub in one deployment and spoke in other deployment. I’m just planning to do like an automation.

**Comment by jtracey93** [comment]
Hey @ArthiSaravana,

We are working on an accelerator repo but this will mainly be "production ready" GitHub actions etc. but will still do it all in separate deployments orchestrated by the pipeline. 

Interested to understand "why" you want to do in a single deployment instead of orchestrating in a pipeline etc? Which still achieves the same end result and gives you a bit more control over the deployment. 

If you want to do in a single deployment you can use the scope functions to tell ARM to change between different subscriptions etc as part of a single deployment as per https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-scope#subscription

Finally, if you are looking at vending subscriptions for spokes also then I suggest looking at https://aka.me/LZ-vending/bicep which can handle the subscription creation as well as management group placement and platform spoke networking and peering amongst other things. 👍 (we also created this module) 

Thanks

Jack

**Comment by ArthiSaravana** [comment]
This is my manager requirement to do it in a single deployment if possible. you know right, its like an automation.

**Comment by ArthiSaravana** [comment]
Thank you jtracey. I will do that
