### ISSUE TITLE
❓👂 Question/Feedback - Customisation and Keeping Clone of Repo Up To Date

### ISSUE THREAD

**Issue by parallo-mattallford** [Azure/ALZ-Bicep#435]
## Question/Feedback

Hey team.

I wanted to start a discussion around the topic of how best to keep clones / forks of this repository up to date, while maintaining flexibility of being able to customise some of the ALZ-Bicep Modules. Now, it is entirely possible that we are missing something, or overthinking things, but let me expand a little further on this below and see where the conversation leads.

For context, we are a Microsoft partner, and we will often be helping customers with the architecture and implementation of their Azure environment, starting of course with a landing zone.

The discussion _always_ comes up as to how best to consume the ALZ-Bicep repository published here, but with the following requirements:

- Make it easy to customise modules to suit the customers' requirements and design. There is almost always a slight deviation in the customers' deployment when compared to the vanilla templates, for one reason or another, as you've eluded to in [the consumer guide](https://github.com/Azure/ALZ-Bicep/wiki/ConsumerGuide#customizing-the-alz-bicep-modules)
- Have the ability to easily pull in updates from the `Azure/ALZ-Bicep` repo at a later date

To expand a little on the second point, I think it is fair to say that over time the recommendations from Microsoft on what a landing zone contains will change, and there will be additional features and resources published here in the repository moving forward (new resources, new policies, changes to resources / policies, etc).

I wanted to reach out to get some opinions from the community and from the ALZ-Bicep team on how we might be best to approach this, to ensure we are giving customers a stable and robust starting point for their Bicep based Azure Landing Zone, while being able to accommodate customisations and ease of updates to their own copy of this repo in the future.

## Possible Answers/Solutions?

Some ideas we've investigated to date, after taking a clone of the `Azure/ALZ-Bicep` repo include:
1. Create a separate directory where we / the customer can place customised Bicep modules.

This would typically start with cloning the bicep module from the `infra-as-code` directory as a starting point, but then making the required tweaks and changes. The idea behind this is that it provides flexibility in the future to:
- Create a new branch
- Get the latest copy of the `Azure/ALZ-Bicep` repo and store it in the new branch
- Create a PR to `main` and observe what changes there are between when this process was last done (or the initial clone of the `Azure/ALZ-Bicep` repo), and the latest updates that have been made to `Azure/ALZ-Bicep` repo
- If any of these changes were to Bicep files that have been customised by the customer, they need to be aware of this, and merge those changes in to the customised Bicep module as well, if they want to incorporate the changes in to their deployment, as they would be using the customised bicep files for the ALZ deployment, rather than the ones provided in the `infra-as-code` directory

2. Creating a top level orchestration Bicep file to deploy the entire landing zone

This doesn't necessarily relate to the updating / customisation specifically, but it does allow us to have a single Bicep file to orchestrate the landing zone deployment, and then use customised modules as sub-modules of the orchestration bicep file for the deployment. We _could_ of course do this in a pipeline/workflow as well and just reference the customised module instead of the default module, but I noticed an orchestration module for the entire landing zone was also on your backlog, so I thought it might be an interesting thing to raise here that we've started looking in to (could be worth a call with our team to discuss?).

**Comment by jtracey93** [comment]
Hey @parallo-mattallford,

Thanks for raising this issue. It is indeed something we agree we want to cover and our currently working on behind the scenes. 

We are in the process of creating an ALZ Bicep Accelerator repo that will be a GitHub template repo that you can use and it will contain a recommended way of consuming ALZ Bicep and a path to stay up to date with our releases. 

We plan to have this ready sometime around March as we currently stand. 

However, we have already done a lot of the thinking especially around the staying up to date piece. And in fact on the bicep-LZ-vending repo I have created additional guidance on this with a github action that watches the repo releases and creates a PR when things change etc. 

It is effectively just a GitHub action plus a powershell script. But it's already built to be super flexible to work on any repo and select specific directories. 

You can check this out here: https://github.com/azure/bicep-lz-vending/wiki/consumerguide#creating-your-own-github-repository--utilizing-the-invoke-githubreleasefetcherps1-script--gh-release-checkeryml-github-action-workflow 

Feel free to give it a go and let us know your thoughts. 

We are likely heading towards the separate workflows/pipelines path rather than a large orchestration module to be honest as we have heard this is more the desired path from our field and customers. However, we will still create and orchestration module or two to address some requests for it. 

From a consumer repo structure we are going to suggest using the above mentioned GitHub action to sync into a directory called releases (but you could change this to whatever you like) and then any customisations we are going to advise that you copy that module or create a new module in a directory in a directory called our-modules (naming tbc, but again can be changed). 

The key is to keep them separate so pulling in upstream updates is much easier and less chance, if ever, of merge conflicts. 

Let us know your thoughts but happy to have a call once you've digested. Myself and @oZakari are working on this so ping us back here when you are ready to arrange a call based on the above. 

Thanks

Jack

**Comment by parallo-mattallford** [comment]
Hey @jtracey93!

Mate, thanks for the quick and detailed reply.

That all makes sense at a first-pass through. Let me share this with the team on my side, and give us a bit of time to digest it and put some thoughts together. After that a call might be good to talk a few of these items through!

The comment around heading towards separate workflows is an interesting one. Do you mean a separate workflow per Bicep module being deployed for the landing zone? Would be curious to understand this, and the thinking behind it a little more. For us from a high level, it'd make sense to rerun the entire LZ deployment each time, rather than run individual modules / components, but could be missing something here :)

Thanks again Jack, really appreciate it.

Cheers, Matt.

**Comment by jtracey93** [comment]
The accelerator is now live https://github.com/Azure/ALZ-Bicep/wiki/Accelerator
