### ISSUE TITLE
Set variable resource name as a parameter

### ISSUE THREAD

**Issue by amp-pds** [Azure/ALZ-Bicep#610]
### Contact Details

alan.phillips@pds.police.uk

### Describe the feature end to end, including deployment scenario details under which the feature would occur.

Hi,

In hubVirtualNetworkConnection.bicep the name of the VHub connection is defined by a variable.

To provide more flexibility with naming is it possible to have naming variables provided as parameters instead?

In this case the following variable.

var varVnetPeeringVwanName = '${varVwanHubName}/${varSpokeVnetName}-vhc'

Thanks.

### Why is this feature important. Describe why this would be important for your organization and others. Would this impact similar orgs in the same way?

The provided naming does not align to our naming standards, we put the resource abbreviation, in this case vhc- at the start of resources as suggested in MS doc https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming.

Other option would be to keep the variable as follows which would align to our standard, but does not offer flexibility to all.

var varVnetPeeringVwanName = 'vhc-${varVwanHubName}/${varSpokeVnetName}'

### Version

v0.16.1

### check previous github issues

- [X] This feature does has not been requested according to the current issue list

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtracey93** [comment]
Hi @amp-pds,

This name is quite a low level resource that not many really worry about naming, if using the portal it just creates a random string.

We cant make this possible though `var varVnetPeeringVwanName = 'vhc-${varVwanHubName}/${varSpokeVnetName}'` as the `/` is used to define the parent resource, which must be the VWAN Hub Name, otherwise the template will fail.

I will introduce a prefix and suffix parameter for the connection name, something like this for the VHC:

```bicep
var varVnetPeeringVwanName = '${varVwanHubName}/${parVirutalHubConnectionPrefix}${varSpokeVnetName}${parVirtualHubConnectionSuffix}'
```

I will include this with the routing intent changes also
