### ISSUE TITLE
❓👂 Question/Feedback - Utilising CARML project for building ALZ

### ISSUE THREAD

**Issue by samuelya** [Azure/ALZ-Bicep#618]
I'm curious about Microsoft's decision not to leverage the [ResourceModules](https://github.com/Azure/ResourceModules) CARML project for constructing ALZ solution. 

- Wouldn't using existing module components to build ALZ orchestration solution instead of creating new modules from the ground up make things easier?

**Comment by jtracey93** [comment]
Hey @samuelya, good question.

CARML didn't actually exist when we started ALZ-Bicep, we were involved in CARMLs development also and still are today, so this is the primary reason.

We are actually working on the evolution of CARML into something "bigger and even better" at the moment as one big group internally that we'll be able to share more on soon (months). 

And then when that is announced we may start considering at a point in time migrating some of the module in ALZ-Bicep to CARML/CARML v2.

But an important thing to remember that due to the way CARML works with modules, that means a lot of deployments in ARM and that can add latency/slow performance to deployments when they are large, like ALZ. So for example the custom policy definitions module will never be built of CARML for this reason.

If you deployed all the custom policies with CARMLs module today it would take over 45 mins, with the ALZ-Bicep module its about 2 minutes, just due to the fact of less deployments being created and looping.

> It is something we have on our backlog in ALZ Bicep and when the time is right, we will consider doing this, where it makes sense.
