### ISSUE TITLE
Roadmap and known issues

### ISSUE THREAD

**Issue by MilesCameron-DMs** [Azure/ALZ-Bicep#703]
### Let us know the feedback or general question

Hi guys,

I believe we need a publicly facing roadmap and known issues section.

From my own experience, i would have done things differently, planned and allocated more time to certain areas and certainly have wasted less time if this was available.

I can see there was a project with a backlog before but this was canned.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @MilesCameron-DMs, great ask with these and appreciate the transparency with your feedback.

For the known issues, I've created a backlog item so that we can work towards setting up a wiki page dedicated to them, similar to what was done for the Bicep-LZ-Vending repo.

As for why project/roadmap within GitHub was removed in May 2022, I am not sure as I was not a member of the team at that time. However, I will check with @jtracey93 and a couple of others internally to see if they can add some context and potentially see if that is something we can consider adding back. Most people are heading out for vacations, but I will see if I can get an update for you before we get into the new year.

**Comment by MilesCameron-DMs** [comment]
Thanks again @oZakari 👍

**Comment by oZakari** [comment]
@MilesCameron-DMs, discussed with the rest of the team this morning and I will be working on re-establishing a roadmap. It won't illustrate our full backlog, but I am going to include what we have in-progress for the current sprint as well as items we have committed to.

**Comment by MilesCameron-DMs** [comment]
@oZakari that's great news - appreciate it

**Comment by oZakari** [comment]
Hey @MilesCameron-DMs, just sharing the roadmap that has been created which includes user stories from our internal Azure DevOps. Some of the descriptions have redactions so if there are any questions about anything, please let me know and I can try to add clarity.

Adding @johnlokerse for visibility as well!

**Comment by oZakari** [comment]
For anyone looking to regularly check the roadmap from within ALZ-Bicep. Please see the screenshot: 
![image](https://github.com/Azure/ALZ-Bicep/assets/30884663/5054e288-dfdd-4cd5-9524-7de5fc75dcde)

**Comment by MilesCameron-DMs** [comment]
> Hey @MilesCameron-DMs, just sharing the ALZ-Bicep [roadmap ](https://github.com/orgs/Azure/projects/610)that has been created which includes user stories from our internal Azure DevOps. Some of the descriptions have redactions so if there are any questions about anything, please let me know and I can try to add clarity.
> 
> Along with that, I've linked the all-up ALZ public roadmap to this repository as well for additional visibility.
> 
> Adding @johnlokerse for visibility as well!

Excellent news! That is super useful. Thanks @oZakari
