### ISSUE TITLE
Logging module does not specify a SKU for the Automation Account

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/ALZ-Bicep#832]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Deployments of the automation account are successful but because they don't specify a SKU, each subsequent run will try to "remove" the `sku.name` property from the Automation Account.

In other words, there is never a deployment without changes.

### Please provide the correlation id associated with your error or bug.

32fc3ad6-7c12-4fee-b9b2-e33d31bd9af4

### What was the expected outcome?

A subsequent run without parameter changes should result in a deployment without changes.

### Relevant log output

```Shell
~ Microsoft.Automation/automationAccounts/alz-prod-aa-scus-01 [2022-08-08]
    - properties.disableLocalAuth: false
    - properties.RuntimeConfiguration:
 
        powershell.builtinModules.Az:   "11.2.0"
        powershell7.builtinModules.Az:  "8.0.0"
        powershell72.builtinModules.Az: "11.2.0"
 
    x properties.sku.name:         "Basic"
```

### Check previous GitHub issues

- [X] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @SvenAelterman, we do set the SKU to `Basis` in the module. This appears to be a bug with the Azure Automation resource provider with API version `2023-11-01`. If you look at the properties of the deployed resource you'll see that the SKU is set to Basic. 

As this is related to the provider, please open an issue within the[ Azure Bicep repo](https://github.com/Azure/bicep/issues) so that the product team can investigate.
