### ISSUE TITLE
Do we have to remove the assignments 'Deploy-VM-Monitoring' and 'Deploy-VMSS-Monitoring'?

### ISSUE THREAD

**Issue by baartch** [Azure/ALZ-Bicep#867]
With the _Policy Refresh H2 FY24_ coming with version `v0.18.0` you removed the two policy assignments:

- Deploy-VM-Monitoring (Initiative: [55f3eceb-5573-4f18-9695-226972c6d74a](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/55f3eceb-5573-4f18-9695-226972c6d74a.html))
- Deploy-VMSS-Monitoring (Initiative: [75714362-cae7-409e-9b99-a8e5075b7fad](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/75714362-cae7-409e-9b99-a8e5075b7fad.html))

in the file `infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep`.
Both Initiatives are marked as _Legacy_, since they deploy the old _Log Analytics extension_.
In the [Cleanup](https://github.com/Azure/ALZ-Bicep/releases/tag/v0.18.0) steps of v0.18.0 you don't mention to remove these two assignments. Isn't this missing?

Thank you for your answer.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hi @baartch! You're correct, since the IDs changed the original policy assignments need to be removed. I have updated the release notes and also updated the policy assignment names in this [PR ](https://github.com/Azure/ALZ-Bicep/pull/806/files#diff-ffc57ec7d7d07fc489016add5b1301ed78dd4ca65c2ec4f74648dd25a93b44f5) to what they are set to in the comments of the alzDefaultPolicyAssignments.bicep file.
