### ISSUE TITLE
Cannot retrieve the dynamic parameters for the cmdlet.

### ISSUE THREAD

**Issue by plaaard** [Azure/ALZ-Bicep#919]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Hello

I'm trying to get started with the ALZ-Bicep repo and deploy management groups, I've updated the parameters file and when trying to run the below to deploy to my Azure tenant I get an error:

>>  `$inputObject = @{
 DeploymentName        = -join ('alz-MGDeployment-{0}' -f (Get-Date -Format 'yyyyMMddTHHMMssffffZ'))[0..63]
>>   Location              = 'UKSouth'
>>   TemplateFile          = "infra-as-code/bicep/modules/managementGroups/managementGroups.bicep"
>>   TemplateParameterFile = 'infra-as-code/bicep/modules/managementGroups/parameters/managementGroups.parameters.all.json'
New-AzTenantDeployment @inputObject
>> }`

_New-AzTenantDeployment: Cannot retrieve the dynamic parameters for the cmdlet. Cannot find Bicep. Please add Bicep to your PATH or visit https://aka.ms/bicep-install to install Bicep._

I've looked at the FAQ page [https://github.com/Azure/ALZ-Bicep/wiki/FAQ](url) which mentions the error and advises to update Bicep which I've done:

![Image](https://github.com/user-attachments/assets/ef033d53-0ae9-453a-b32a-1c2acda1295d)

I'm still receiving the same error as mentioned above post update of bicep, can someone please advise?.

### Please provide the correlation id associated with your error or bug.

N/A

### What was the expected outcome?

Deploy MG's to AZ tenant.

### Relevant log output

```Shell

```

### Check previous GitHub issues

- [x] I have searched the issues for this item and found no duplicate

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oZakari** [comment]
Hey @plaaard, 

Thanks for reaching out! I'm happy to help with your ALZ-Bicep journey. 

When it comes to installing Azure Bicep, there are a few approaches to consider. Based on your screenshot, it looks like you're using `az bicep version`, which is tied to the Azure CLI and not accessible via PowerShell. You can verify your Bicep installation for use with PowerShell by running `bicep --version`. Alternatively, you can use the following [Azure CLI command](https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/managementGroups#azure-cli---managementgroupsbicep) for deployment instead of PowerShell if you want to give that a try which should work for you.

On the other hand, if you'd like to use PowerShell, you'll need to manually install the Bicep CLI and add it to your system's path. Follow the instructions [here](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#install-manually) for your specific operating system.

Will close this for now, but if you are still running into issues, feel free to just respond back on this thread.

**Comment by plaaard** [comment]
I seemed to get this working via:

# Create the install folder
$installPath = "$env:USERPROFILE\.bicep"
$installDir = New-Item -ItemType Directory -Path $installPath -Force
$installDir.Attributes += 'Hidden'
# Fetch the latest Bicep CLI binary
(New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")
# Add bicep to your PATH
$currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }
# Verify you can now access the 'bicep' command.
bicep --help
# Done!

Thanks :-)
